=== DiprajMo/Practica-6/file.dtd
<!ELEMENT luxuria (luxuriastock*,luxuriaclients+)>
<!ELEMENT luxuriastock (samarretes_menu?,jerseis_menu?,jaquetes_menu?,pantalons_menu?)>
<!ELEMENT samarretes_menu (samarretes+)>
<!ELEMENT samarretes (samarretes_curtes*,samarretes_llargues?)>
<!ELEMENT samarretes_curtes (Be_free? , Berna?, Skyline?)>

<!ELEMENT Be_free (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
    <!ATTLIST Be_free producteID ID #REQUIRED>

<!ELEMENT Berna (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Berna producteID ID #REQUIRED>

<!ELEMENT Skyline (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Skyline producteID ID #REQUIRED>

<!ELEMENT samarretes_llargues (Looong_Shirt?,Terra_Nova?)>
<!ELEMENT Looong_Shirt (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Looong_Shirt producteID ID #REQUIRED>

<!ELEMENT Terra_Nova (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Terra_Nova producteID ID #REQUIRED>

<!ELEMENT jerseis_menu (jerseis)>
<!ELEMENT jerseis (Garfield?,Doraemon?)>
<!ELEMENT Garfield (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Garfield producteID ID #REQUIRED>

<!ELEMENT Doraemon (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Doraemon producteID ID #REQUIRED>

<!ELEMENT jaquetes_menu (jaquetes)>
<!ELEMENT jaquetes (jaquetes_de_entretemps?,jaquetes_hivern?,jaquetes_de_neu?)>

<!ELEMENT jaquetes_de_entretemps (Diesel?,Rain?)>
<!ELEMENT Diesel (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Diesel producte ID #REQUIRED>

<!ELEMENT Rain (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Rain producteID ID #REQUIRED>

<!ELEMENT jaquetes_hivern (December?)>
<!ELEMENT December (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST December producteID ID #REQUIRED>

<!ELEMENT jaquetes_de_neu (Snow?)>
<!ELEMENT Snow (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Snow producteID ID #REQUIRED>

<!ELEMENT pantalons_menu (pantalons)>
<!ELEMENT pantalons (pantalons_curts?,pantalons_llargs?)>
<!ELEMENT pantalons_curts (Beach?,Travel?)>

<!ELEMENT Beach (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Beach producteID ID #REQUIRED>

<!ELEMENT Travel (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Travel producteID ID #REQUIRED>

<!ELEMENT pantalons_llargs (Jeans1?,Jeans2?)>
<!ELEMENT Jeans1 (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Jeans1 producteID ID #REQUIRED>

<!ELEMENT Jeans2 (nom,preu,color,descripcio,talles,material,quantitat,sexe)>
<!ATTLIST Jeans2 producteID ID #REQUIRED>

<!ELEMENT luxuriaclients (registre_clients)>
<!ELEMENT registre_clients (clients)>
<!ELEMENT clients (client1,client2,client3,client4,client5)>

<!ELEMENT client1 (nom,email,adreça,compra)>
<!ATTLIST client1 id ID #REQUIRED>
<!ELEMENT compra (compra1,compra2)>
<!ATTLIST compra1 productID CDATA #REQUIRED>
<!ATTLIST compra1 date CDATA #REQUIRED>
<!ELEMENT compra1 (#PCDATA)>

<!ELEMENT client2 (nom,email,adreça,compras)>
<!ATTLIST client2 id ID #REQUIRED>
<!ELEMENT compras (compra1,compra2,compra3,compra4)>
<!ATTLIST compra2 productID CDATA #REQUIRED>
<!ATTLIST compra2 date CDATA #REQUIRED>
<!ELEMENT compra2 (#PCDATA)>
<!ATTLIST compra3 productID CDATA #REQUIRED>
<!ATTLIST compra3 date CDATA #REQUIRED>
<!ELEMENT compra3 (#PCDATA)>
<!ATTLIST compra4 productID CDATA #REQUIRED>
<!ATTLIST compra4 date CDATA #REQUIRED>
<!ELEMENT compra4 (#PCDATA)>

<!ELEMENT client3 (nom,email,adreça,compras1)>
<!ATTLIST client3 id ID #REQUIRED>
<!ELEMENT compras1 (compra1,compra2,compra3,compra4)>

<!ELEMENT client4 (nom,email,adreça,compras4)>
<!ATTLIST client4 id ID #REQUIRED>
<!ELEMENT compras4 (compra1,compra2,compra3,compra4)>

<!ELEMENT client5 (nom,email,adreça,compras5)>
<!ATTLIST client5 id ID #REQUIRED>
<!ELEMENT compras5 (compra1,compra2,compra3,compra4)>







<!ELEMENT adreça (calle,ciutat,postal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciutat (#PCDATA)>
<!ELEMENT postal (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT preu (#PCDATA)>
<!ATTLIST preu moneda CDATA #REQUIRED>
<!ELEMENT color (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT talles (#PCDATA)>
<!ATTLIST talles talla_pais CDATA #REQUIRED>
<!ELEMENT material (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT sexe (#PCDATA)>



<!--<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT adreca (carrer, num, cp)>
<!ELEMENT carrer (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ATTLIST tlf pais CDATA  #REQUIRED>
-->

=== DiprajMo/Practica-6/luxuria.xml
<?xml version="1.0" encoding="UTF-8"?> <!-- Estructura XML per a l'estoc del negoci i gestió dels clients del negoci -->
<!DOCTYPE luxuria SYSTEM "file.dtd">
<luxuria> <!-- L'empresa--> 
    <luxuriastock> <!--stock de la tenda-->
        <samarretes_menu> <!--menu de les samarretes-->
            <samarretes>
                 <!--apartat de samarretes-->
                <samarretes_curtes> <!--tipus de samarreta-->
                    <Be_free producteID="BF100"> <!--nom de la samarreta curta-->
                        <nom> Be free </nom> <!--nom-->
                        <preu moneda="dòlar"> $29.99 </preu> <!--preu-->
                        <color> Blanc, negre, blau </color> <!--color-->
                        <descripcio> Aquesta samarreta té un ocell volant, senzill però elegant. Colors clars </descripcio> <!--descripció del producte-->
                    <talles talla_pais="EU"> XS, S, M, L, XL, XXL, XXXL </talles> <!--talla-->
                        <material>80% cotó, 20% poliester </material> <!--material--> 
                        <quantitat> 50 per talla </quantitat> <!--quantitat de producets disponibles-->
                        <sexe> Unisex </sexe> <!--vestimenta dedicada per homes i dones-->
                    </Be_free>
                    <Berna producteID="BA200"> <!--nom de la samarreta curta-->
                        <nom> Berna </nom> <!--nom-->
                        <preu moneda="dòlar"> $29.99 </preu> <!--preu-->
                        <color> Verd, blau, gris, blanc, marró </color> <!--color-->
                        <descripcio> representa la ciutat de Berena amb colors verd bosc, colors càlids</descripcio> <!--descripció del producte-->
                        <talles talla_pais="EU"> XS, S, M, L, XL, XXL, XXXL </talles> <!--talla-->
                        <material> 90% cotó, 10% polièster </material> <!--material-->
                        <quantitat> 50 per talla </quantitat> <!--quantitat de producets disponibles-->
                        <sexe> Unisex </sexe> <!--vestimenta dedicada per homes i dones-->
                    </Berna>
                    <Skyline producteID="SL300"> <!--nom de la samarreta curta-->
                        <nom> Skyline </nom> <!--nom-->
                        <preu moneda="dòlar"> $29.99 </preu> <!--preu-->
                        <color> Blau, negre, gris, verd, groc, blanc</color> <!--color-->
                        <descripcio> Samarreta dels gratacels de Nova York, amb un ocell sobrevolant l'illa. </descripcio> <!--descripció del producte-->
                        <talles talla_pais="EU"> XS, S, M, L, XL, XXL, XXXL </talles> <!--talla-->
                        <material> 50% cotó, 50% polièster </material> <!--material-->
                        <quantitat> 50 per talla </quantitat> <!--quantitat de producets disponibles-->
                        <sexe> Unisex </sexe> <!--vestimenta dedicada per homes i dones-->
                    </Skyline>
                </samarretes_curtes>
                <samarretes_llargues>
                    <Looong_Shirt producteID="IP400">
                        <nom> Looong Shirt</nom><!--nom-->
                        <preu moneda="dòlar"> $35.99 </preu> <!--preu-->
                        <color> Blanc </color> <!--color-->
                        <descripcio> Samarreta llarga blanca bàsica, ideal per vestir amb un tacte suau. </descripcio> <!--descripció del producte-->
                        <talles talla_pais="EU"> XS, S, M, L, XL, XXL, XXXL </talles> <!--talla-->
                        <material>80% cotó, 20% poliester </material> <!--material-->
                        <quantitat> 30 per talla </quantitat> <!--quantitat de producets disponibles-->
                        <sexe> Unisex </sexe> <!--vestimenta dedicada per homes i dones-->
                    </Looong_Shirt> 
                    <Terra_Nova producteID="TN500">
                        <nom> Terra Nova</nom><!--nom-->
                        <preu moneda="dòlar"> $35.99 </preu> <!--preu-->
                        <color> Negre, gris </color> <!--color-->
                        <descripcio> Samarreta llarga fosca d'estil urbà ideal per el dia a dia. </descripcio> <!--descripció del producte-->
                        <talles talla_pais="EU"> S, M, L, XL, XXL, XXXL </talles> <!--talla-->
                        <material>70% cotó, 30% poliester </material> <!--material-->
                        <quantitat> 30 per talla </quantitat> <!--quantitat de producets disponibles-->
                        <sexe> Unisex </sexe> <!--vestimenta dedicada per homes i dones-->
                    </Terra_Nova> 
                </samarretes_llargues>
            </samarretes>
        </samarretes_menu>
        <jerseis_menu>
            <jerseis>
                <Garfield producteID="G600">
                    <nom> Garfield</nom><!--nom-->
                    <preu moneda="dòlar"> $39.99 </preu> <!--preu-->
                    <color> Taronja, groc, blanc, negre, vermell </color> <!--color-->
                    <descripcio> Jersei taronja amb un dibuix estampat del icònoc gat "Garfield". </descripcio> <!--descripció del producte-->
                    <talles talla_pais="EU"> S, M, L, XL, XXL, XXXL </talles> <!--talla-->
                    <material>85% cotó, 15% poliester </material> <!--material-->
                    <quantitat> 35 per talla </quantitat> <!--quantitat de producets disponibles-->
                    <sexe> Unisex </sexe> <!--vestimenta dedicada per homes i dones-->
                </Garfield> 
                <Doraemon producteID="D700">
                    <nom> Doraemon</nom><!--nom-->
                    <preu moneda="dòlar"> $39.99 </preu> <!--preu-->
                    <color> Negre, gris </color> <!--color-->
                    <descripcio> Jersei blau amb el dibuix estampat del Doraemon, amb el text blanc a sota del dibuix: "el gat còsmic"</descripcio> <!--descripció del producte-->
                    <talles talla_pais="EU"> S, M, L, XL, XXL, XXXL </talles> <!--talla-->
                    <material>70% cotó, 30% poliester </material> <!--material-->
                    <quantitat> 35 per talla </quantitat> <!--quantitat de producets disponibles-->
                    <sexe> Unisex </sexe> <!--vestimenta dedicada per homes i dones-->
                </Doraemon>
            </jerseis>
        </jerseis_menu>
        <jaquetes_menu>
            <jaquetes>
                <jaquetes_de_entretemps> 
                    <Diesel producte="D800">
                        <nom> Diesel</nom><!--nom-->
                        <preu moneda="dòlar"> $59.99 </preu> <!--preu-->
                        <color> Negre, marró, gris, blau </color> <!--color-->
                        <descripcio> Jaqueta fina inspirada en un estil americà, de motorista popular dels anys 80's. </descripcio> <!--descripció del producte-->
                        <talles talla_pais="EU"> M, L, XL, XXL, XXXL </talles> <!--talla-->
                        <material>70% pell, 30% cuir </material> <!--material-->
                        <quantitat> 25 per talla </quantitat> <!--quantitat de producets disponibles-->
                        <sexe> home </sexe> <!--vestimenta dedicada per homes-->
                    </Diesel>
                    <Rain producteID="R900">
                        <nom> Rain</nom><!--nom-->
                        <preu moneda="dòlar"> $59.99 </preu> <!--preu-->
                        <color> Blanc, marró, gris, negre, blau, verd </color> <!--color-->
                        <descripcio> Jaqueta fina que amb els seus colors difuminats representa amb una silueta un paissatge muntanyós. </descripcio> <!--descripció del producte-->
                        <talles talla_pais="EU"> M, L, XL, XXL, XXXL </talles> <!--talla-->
                        <material>70% pell, 30% cuir </material> <!--material-->
                        <quantitat> 25 per talla </quantitat> <!--quantitat de producets disponibles-->
                        <sexe> dona </sexe> <!--vestimenta dedicada per dones-->
                    </Rain>
                </jaquetes_de_entretemps>
                <jaquetes_hivern> 
                    <December producteID="D1000">
                        <nom> December</nom><!--nom-->
                        <preu moneda="dòlar"> $79.99 </preu> <!--preu-->
                        <color> Blanc, gris negre</color> <!--color-->
                        <descripcio> Jaqueta gruixuda i gran amb un estil senzill de 3 capes de colors (blanc, gris, negre) </descripcio> <!--descripció del producte-->
                        <talles talla_pais="EU"> M, L, XL, XXL, XXXL </talles> <!--talla-->
                        <material>70% pell, 30% cotó </material> <!--material-->
                        <quantitat> 20 per talla </quantitat> <!--quantitat de producets disponibles-->
                        <sexe> home </sexe> <!--vestimenta dedicada per homes-->
                    </December>
                </jaquetes_hivern>
                <jaquetes_de_neu> 
                    <Snow producteID="S1100">
                        <nom> Snow </nom><!--nom-->
                        <preu moneda="dòlar"> $89.99 </preu> <!--preu-->
                        <color> Blau, negre i gris </color> <!--color-->
                        <descripcio> Jaqueta gruixuda i dissenyada per resistir baixes temperatures amb un estil blau, negre i gris clar. </descripcio> <!--descripció del producte-->
                        <talles talla_pais="EU"> M, L, XL, XXL, XXXL </talles> <!--talla-->
                        <material>70% pell, 30% poliester </material> <!--material-->
                        <quantitat> 20 per talla </quantitat> <!--quantitat de producets disponibles-->
                        <sexe> Unisex </sexe> <!--vestimenta dedicada per homes i dones-->
                    </Snow>
                </jaquetes_de_neu>
            </jaquetes>
